### ISSUE TITLE
G0 commands set feedrate greater than max_feedrate

### ISSUE THREAD

**Issue by DeanCording** [markwal/GPX#2]
I had reason to delve into the code and the following line struck me as odd when processing the G0 g-code:

```
4479:  feedrate = gpx->machine.x.max_feedrate * length / delta.x;
```

length of the vector from the current position to the requested position
delta.x is the x axis component of that vector
max_feedrate is te maximum feedrate of the axis

It's not too clear what the intention of this code is, but it appears that this and the corresponding lines for Y and Z axis scale the feedrate by the distance the extruder has to travel.

However as length >= delta.x, length/delta.x will always be greater than 1 and therefore feedrate will always be greater that max_feedrate.

Even then, queue_ext_point appears to ignore the supplied feedrate and calculate its own using get_safe_feedrate.  

get_safe_feedrate seems even more screwed up with code like:

```
719:    if(flag & X_IS_SET && (feedrate * delta->x / distance) > gpx->machine.x.max_feedrate) {
      feedrate = gpx->machine.x.max_feedrate * distance / delta->x;
  }
```

How does this calculate any sane value?

**Comment by markwal** [comment]
GPX (from before I forked it), interprets G1 as precise movement and G0 as rapid positioning as per gcode definition.  Most reprap firmwares that take gcode directly treat G0 and G1 equivalently.  In the GPX switch statement, it calculates the feedrate from the maximum for G0.  But...  It looks like me that either way it calls queue_ext_point which always stomps on the passed in value with the result of get_safe_feedrate.  Which is a little weird.

Let's look at the delta->z == 0 case so we can think in 2D.  In this case, distance is the hypotenuse of the right triangle with other sides being delta->x and delta->y.  Then feedrate \* delta->x / distance is the magnitude of the vector on the x axis (or the x feedrate) which it tests against x max feedrate.  And if it exceeds the x max feed rate. It sets the feedrate to the feedrate that results from the x max feedrate projected out onto the hypotenuse.  It checks the max feedrate in order of X, then Y then Z and any hit will stomp on the result before.

When it finally passes the feedrate to the x3g 155 command, it passes the feedrate for the entire move vector (all axes), so the weird math you are seeing is because the maximum's are specified for each axis independently.
