### ISSUE TITLE
What gcode flavor should I use in Slic3r/Sailfish?

### ISSUE THREAD

**Issue by mron** [markwal/GPX#22]
What gcode flavor do you set in Slic3r? I have a FFCP with Sailfish firmware. Sailfish is supposed to be ReplicatorG gcode. I cannot get proper Dual extrusion behavior out of gpx with either -g or -r. With -g, the tool switches work but the bed is heated to the tool temp. With -r the bed temp is fine but the extruders won't switch.

**Comment by markwal** [comment]
I set "RepRap Marlin" flavor in Slic3r and use "-r" flag to gpx. 

Somebody convinced Slic3r to use M108 Tn as the tool change gcode for "Sailfish" flavor which IMHO is just wrong.  That is ReplicatorG only and is weird because it isn't even what MakerBot generated for toolchange (it had used M108 earlier for the old extruder RPM).  As far as I know, MakerBot has used M135 Tn for toolchange for a long while now.  That's not a good solution either because it is for "Set PID interval" stuff on other firmwares.

If you need/want to use "Sailfish" flavor whatever that means, you can workaround this a couple of ways.  One is to update to a later version of GPX since I added support for that weird M108 (though I haven't tried it lately).  Another is to put "T[next_extruder]" in the tool change gcode in Slic3r since that'll just double up on the M108 and one of them will do it.

But like I say, I recommend RepRap flavor.
